"""Google Drive service.

Supports two auth methods (checks in this order):
  1. OAuth2 token  — token.json  (generated by auth_drive.py, recommended)
  2. Service Account — credentials.json  (if SA key creation is allowed in your org)

Folder structures created automatically:
  Party_Invoices/
    {Entity}/
      Purchase Invoices | Sale Invoices/
        {FY}/
          {Party Name}/
            {Month}/

  Month_Invoices/
    Purchase | Sale/
      {FY}/
        {Month}/
"""

import logging
import os

from googleapiclient.discovery import build
from googleapiclient.http import MediaFileUpload
from config import GOOGLE_CREDENTIALS_FILE

logger = logging.getLogger(__name__)
_SCOPES = ["https://www.googleapis.com/auth/drive"]

_TOKEN_FILE = "token.json"          # OAuth2 Desktop flow
_SA_FILE = GOOGLE_CREDENTIALS_FILE  # Service account JSON


def _get_credentials():
    """Return valid Google credentials, preferring OAuth2 over service account."""
    # ── OAuth2 token (Desktop App) ─────────────────────────────────────────────
    if os.path.isfile(_TOKEN_FILE):
        from google.oauth2.credentials import Credentials
        from google.auth.transport.requests import Request

        creds = Credentials.from_authorized_user_file(_TOKEN_FILE, _SCOPES)
        if creds.expired and creds.refresh_token:
            creds.refresh(Request())
            with open(_TOKEN_FILE, "w") as f:
                f.write(creds.to_json())
        return creds

    # ── Service account JSON ───────────────────────────────────────────────────
    if os.path.isfile(_SA_FILE):
        from google.oauth2 import service_account
        return service_account.Credentials.from_service_account_file(
            _SA_FILE, scopes=_SCOPES
        )

    raise FileNotFoundError(
        "No Google Drive credentials found. "
        "Run 'python auth_drive.py' to authorize via browser."
    )


class DriveService:
    def __init__(self):
        creds = _get_credentials()
        self._svc = build("drive", "v3", credentials=creds, cache_discovery=False)
        self._cache: dict[tuple, str] = {}  # (parent_id, name) → folder_id

    def _get_or_create_folder(self, name: str, parent_id: str) -> str:
        key = (parent_id, name)
        if key in self._cache:
            return self._cache[key]

        safe_name = name.replace("'", "\\'")
        q = (
            f"name='{safe_name}' and "
            f"'{parent_id}' in parents and "
            f"mimeType='application/vnd.google-apps.folder' and "
            f"trashed=false"
        )
        res = self._svc.files().list(q=q, fields="files(id)").execute()
        files = res.get("files", [])

        if files:
            folder_id = files[0]["id"]
        else:
            meta = {
                "name": name,
                "mimeType": "application/vnd.google-apps.folder",
                "parents": [parent_id],
            }
            folder = self._svc.files().create(body=meta, fields="id").execute()
            folder_id = folder["id"]

        self._cache[key] = folder_id
        return folder_id

    def get_party_invoices_folder(
        self, entity: str, invoice_type: str, fy: str,
        party_name: str, month_folder: str, root_id: str,
    ) -> str:
        type_dir = "Purchase Invoices" if invoice_type == "purchase" else "Sale Invoices"
        f = self._get_or_create_folder(entity, root_id)
        f = self._get_or_create_folder("Party_Invoices", f)
        f = self._get_or_create_folder(type_dir, f)
        f = self._get_or_create_folder(party_name, f)
        f = self._get_or_create_folder(fy, f)
        f = self._get_or_create_folder(month_folder, f)
        return f

    def get_month_invoices_folder(
        self, entity: str, invoice_type: str, fy: str, month_folder: str, root_id: str,
    ) -> str:
        type_dir = "Purchase" if invoice_type == "purchase" else "Sale"
        f = self._get_or_create_folder(entity, root_id)
        f = self._get_or_create_folder("Month_Invoices", f)
        f = self._get_or_create_folder(type_dir, f)
        f = self._get_or_create_folder(fy, f)
        f = self._get_or_create_folder(month_folder, f)
        return f

    def upload_file(self, local_path: str, filename: str, parent_id: str) -> str:
        """Upload a PDF and return its web view link."""
        meta = {"name": filename, "parents": [parent_id]}
        media = MediaFileUpload(local_path, mimetype="application/pdf", resumable=True)
        file = self._svc.files().create(
            body=meta, media_body=media, fields="id,webViewLink"
        ).execute()
        try:
            self._svc.permissions().create(
                fileId=file["id"],
                body={"type": "anyone", "role": "reader"},
            ).execute()
        except Exception:
            pass  # Non-fatal — file is still saved
        return file.get("webViewLink", "")


def is_configured() -> bool:
    return os.path.isfile(_TOKEN_FILE) or os.path.isfile(_SA_FILE)
